### ISSUE TITLE
Colors dont really match up in <script></script> tags

### ISSUE THREAD

**Issue by muggy8** [classikd/notepad-plus-plus-syntax#2]
Hey there i want to say good job and thanks for the theme. it made my mandatory switch from Windows to Mac and consequently Notepad++ to Atom much easier. However I recently noticed that inlined JS code doesn't seem to have the same styling as the code in a .js file (this could be also true for CSS as well which i will go investigate as soon as i'm done posting here. same may also be true for inline js for php files as well). Here's a screen cap for what I mean thanks ^_^ 

![screen shot 2017-11-28 at 11 24 17 am](https://user-images.githubusercontent.com/5509614/33339716-e8fa9da6-d42e-11e7-83dc-156541393272.png)

**Comment by muggy8** [comment]
![screen shot 2017-11-28 at 11 37 33 am](https://user-images.githubusercontent.com/5509614/33340302-a426d7f6-d430-11e7-9408-2226ab284643.png)
![screen shot 2017-11-28 at 11 37 47 am](https://user-images.githubusercontent.com/5509614/33340310-a8f57f6c-d430-11e7-94a0-6c291600c309.png)
i actually like how Atom handles the inline CSS vs how Wine's Notepad++ handles it. that said The only complaint is that the "{" and the "}" character in the inlined version has the theme's color while. Hopefully this is a bug that's new if not, ignore me i'm an idiot XD

**Comment by classikd** [comment]
Hello,

Indeed you're right, the color is not correct for the code you've tested.
I had some others problems like that, all due to the fact that the Atom markup does not provide enough classes in inlined code. So CSS can't be applied correctly on them :/
Same behavior happens when you add PHP in HTML attributes for instance : 
`<div id="purchase-<?php echo $page['nid']; ?>"> `

I've also noticed some incorrect colors in ES6 syntax, i will try to correct them (tomorrow maybe) and try to see if the Atom team added classes since my last commit.
I will report here if i was able to correct or not inline JS syntax.
Do not hesitate to show me if you see others things like that. 
Thank you

**Comment by classikd** [comment]
Ok, i've made a huge update, i've found so many things to correct.. 
It took me four days instead of one sorry^^
I hope you will enjoy it better now.

**Comment by muggy8** [comment]
whoooo everything looks so much nicer and prettier now :D (at least on my home computer haha xD) thanks :D!!!
